export const phase1StaticStudios = [
  {
    businessCode: 'YL-202609-0006',
    name: '晨光摄影',
    contactName: '周敏',
    contactPhoneMasked: '139****5578',
    balance: '280.000000',
    mcCode: 'MC-CG-102',
    rate: '0.480000',
    erpResultUrl: 'https://erp.chenguang.example/callback',
    erpRecordingUrl: 'https://erp.chenguang.example/recording-callback',
    crmResultUrl: 'https://crm.chenguang.example/callback',
    crmRecordingUrl: 'https://crm.chenguang.example/recording-callback',
    status: 'ACTIVE' as const,
    accountStatus: 'LOW_BALANCE' as const,
    createdAt: new Date('2026-09-02T09:16:24+08:00'),
    createdBy: '王琪',
  },
  {
    businessCode: 'YL-202609-0005',
    name: '罗曼映像',
    contactName: '李卓',
    contactPhoneMasked: '185****0986',
    balance: '-80.500000',
    mcCode: 'MC-LM-064',
    rate: '0.480000',
    erpResultUrl: 'https://erp.luoman.example/callback',
    erpRecordingUrl: 'https://erp.luoman.example/recording-callback',
    crmResultUrl: null,
    crmRecordingUrl: null,
    status: 'ACTIVE' as const,
    accountStatus: 'OVERDUE' as const,
    createdAt: new Date('2026-09-01T16:48:06+08:00'),
    createdBy: '王琪',
  },
  {
    businessCode: 'YL-202609-0004',
    name: '紫藤影像',
    contactName: '陈思',
    contactPhoneMasked: '138****8210',
    balance: '13279.400000',
    mcCode: 'MC-ZTY-001',
    rate: '0.480000',
    erpResultUrl: 'https://erp.ziteng.example/callback',
    erpRecordingUrl: 'https://erp.ziteng.example/recording-callback',
    crmResultUrl: 'https://crm.ziteng.example/callback',
    crmRecordingUrl: 'https://crm.ziteng.example/recording-callback',
    status: 'ACTIVE' as const,
    accountStatus: 'ACTIVE' as const,
    createdAt: new Date('2026-09-01T14:20:31+08:00'),
    createdBy: '王琪',
  },
  {
    businessCode: 'YL-202609-0003',
    name: '远山摄影',
    contactName: '吴倩',
    contactPhoneMasked: '186****1932',
    balance: '4315.800000',
    mcCode: 'MC-YS-028',
    rate: '0.480000',
    erpResultUrl: 'https://erp.yuanshan.example/callback',
    erpRecordingUrl: 'https://erp.yuanshan.example/recording-callback',
    crmResultUrl: null,
    crmRecordingUrl: null,
    status: 'ACTIVE' as const,
    accountStatus: 'ACTIVE' as const,
    createdAt: new Date('2026-08-31T10:12:48+08:00'),
    createdBy: '李萌',
  },
  {
    businessCode: 'YL-202609-0002',
    name: '白屿婚纱摄影',
    contactName: '许宁',
    contactPhoneMasked: '137****1263',
    balance: '860.000000',
    mcCode: 'MC-BY-019',
    rate: '0.480000',
    erpResultUrl: null,
    erpRecordingUrl: null,
    crmResultUrl: 'https://crm.baiyu.example/callback',
    crmRecordingUrl: 'https://crm.baiyu.example/recording-callback',
    status: 'DISABLED' as const,
    accountStatus: 'DISABLED' as const,
    createdAt: new Date('2026-08-29T17:35:09+08:00'),
    createdBy: '王琪',
  },
] as const;

export const phase1SupplierPricingTiers = [
  {
    tierCode: 'tier-basic',
    name: '基础阶梯',
    minMonthlyMinutes: 0n,
    maxMonthlyMinutes: 10_000n,
    voiceRate: '0.200000',
    smsRate: '0.080000',
  },
  {
    tierCode: 'tier-growth',
    name: '成长阶梯',
    minMonthlyMinutes: 10_000n,
    maxMonthlyMinutes: 50_000n,
    voiceRate: '0.180000',
    smsRate: '0.070000',
  },
  {
    tierCode: 'tier-scale',
    name: '规模阶梯',
    minMonthlyMinutes: 50_000n,
    maxMonthlyMinutes: null,
    voiceRate: '0.160000',
    smsRate: '0.060000',
  },
] as const;

export const phase1StaticExpectedCounts = {
  studios: phase1StaticStudios.length,
  accounts: phase1StaticStudios.length,
  pricingVersions: phase1StaticStudios.length,
  endpoints: phase1StaticStudios.reduce(
    (count, studio) =>
      count +
      Number(Boolean(studio.erpResultUrl)) +
      Number(Boolean(studio.crmResultUrl)),
    0,
  ),
  supplierPricingTiers: phase1SupplierPricingTiers.length,
};
